
modLoader="javafml" #mandatory

loaderVersion="[35,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="All rights reserved"

issueTrackerURL="https://github.com/PiscesdanAT/ThinPillars/issues" #optional

[[mods]] #mandatory

modId="thinpillars" #mandatory

version="${file.jarVersion}" #mandatory

displayName="Thin Pillars" #mandatory


credits="A very special thanks and credit goes to HellFirePvP for making the model and associated code, and allowing me to use them." #optional

authors="Piscesdan, HellFirePvP" #optional

description='''
A small mod that adds variants to pillar blocks, shaped like those from Astral Sorcery.
'''

[[dependencies.thinpillars]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.thinpillars]]
    modId="minecraft"
    mandatory=true

[[dependencies.thinpillars]]
    modId="quark"
    mandatory=false
    versionRange="[r2.4-304,)"
    ordering="NONE"
    side="BOTH"

    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"
